-- MySQL Script generated by MySQL Workbench
-- Thu Aug  2 20:47:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bug_tracking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bug_tracking` ;

-- -----------------------------------------------------
-- Schema bug_tracking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bug_tracking` DEFAULT CHARACTER SET utf8 ;
USE `bug_tracking` ;

-- -----------------------------------------------------
-- Table `bug_tracking`.`action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug_tracking`.`action` ;

CREATE TABLE IF NOT EXISTS `bug_tracking`.`action` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bug_tracking`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug_tracking`.`role` ;

CREATE TABLE IF NOT EXISTS `bug_tracking`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `valid_from` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valid_to` DATETIME NULL DEFAULT '9999-12-31 23:59:59',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bug_tracking`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug_tracking`.`employee` ;

CREATE TABLE IF NOT EXISTS `bug_tracking`.`employee` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `role_id` INT(11) NOT NULL,
  `valid_from` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valid_to` DATETIME NULL DEFAULT '9999-12-31 23:59:59',
  PRIMARY KEY (`id`, `role_id`),
  INDEX `fk_employee_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_employee_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `bug_tracking`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bug_tracking`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug_tracking`.`project` ;

CREATE TABLE IF NOT EXISTS `bug_tracking`.`project` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  `valid_from` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valid_to` DATETIME NULL DEFAULT '9999-12-31 23:59:59',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bug_tracking`.`bug`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug_tracking`.`bug` ;

CREATE TABLE IF NOT EXISTS `bug_tracking`.`bug` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `serverity` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `bug_status` VARCHAR(45) NULL DEFAULT NULL,
  `reporter_id` INT(11) NULL DEFAULT NULL,
  `assignee_id` INT(11) NULL DEFAULT NULL,
  `project_id` INT(11) NULL DEFAULT NULL,
  `valid_from` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valid_to` DATETIME NULL DEFAULT '9999-12-31 23:59:59',
  PRIMARY KEY (`id`),
  INDEX `fk_bug_employee_id1_idx` (`reporter_id` ASC),
  INDEX `fk_bug_project_id1_idx` (`project_id` ASC),
  INDEX `fk_bug_assignee_id1_idx` (`assignee_id` ASC),
  CONSTRAINT `fk_bug_assignee_id1`
    FOREIGN KEY (`assignee_id`)
    REFERENCES `bug_tracking`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bug_employee_id1`
    FOREIGN KEY (`reporter_id`)
    REFERENCES `bug_tracking`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bug_project_id1`
    FOREIGN KEY (`project_id`)
    REFERENCES `bug_tracking`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bug_tracking`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug_tracking`.`department` ;

CREATE TABLE IF NOT EXISTS `bug_tracking`.`department` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `level` INT(11) NULL DEFAULT NULL,
  `valid_from` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valid_to` DATETIME NULL DEFAULT '9999-12-31 23:59:59',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bug_tracking`.`dept_emp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug_tracking`.`dept_emp` ;

CREATE TABLE IF NOT EXISTS `bug_tracking`.`dept_emp` (
  `employee_id` INT(11) NOT NULL,
  `dept_id` INT(11) NOT NULL,
  `valid_from` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valid_to` DATETIME NOT NULL DEFAULT '9999-12-31 23:59:59',
  INDEX `fk_dept_emp_employee1_idx` (`employee_id` ASC),
  INDEX `fk_dept_emp_department1_idx` (`dept_id` ASC),
  CONSTRAINT `fk_dept_emp_department1`
    FOREIGN KEY (`dept_id`)
    REFERENCES `bug_tracking`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dept_emp_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `bug_tracking`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bug_tracking`.`employee_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug_tracking`.`employee_project` ;

CREATE TABLE IF NOT EXISTS `bug_tracking`.`employee_project` (
  `status` VARCHAR(10) NOT NULL DEFAULT 'A',
  `valid_from` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valid_to` DATETIME NULL DEFAULT '9999-12-31 23:59:59',
  `employee_id` INT(11) NOT NULL,
  `project_id` INT(11) NOT NULL,
  PRIMARY KEY (`project_id`, `status`, `employee_id`),
  INDEX `fk_employee_project_project1_idx` (`project_id` ASC),
  INDEX `fk_employee_project_employee1` (`employee_id` ASC),
  CONSTRAINT `fk_employee_project_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `bug_tracking`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `bug_tracking`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bug_tracking`.`resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug_tracking`.`resource` ;

CREATE TABLE IF NOT EXISTS `bug_tracking`.`resource` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `valid_from` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valid_to` DATETIME NULL DEFAULT '9999-12-31 11:59:59',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bug_tracking`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug_tracking`.`permission` ;

CREATE TABLE IF NOT EXISTS `bug_tracking`.`permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action_id` INT(11) NOT NULL,
  `resource_id` INT(11) NOT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `valid_from` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valid_to` DATETIME NULL DEFAULT '9999-12-31 11:59:59',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  INDEX `fk_permission_action_id1_idx` (`action_id` ASC),
  INDEX `fk_permission_resource_id1_idx` (`resource_id` ASC),
  CONSTRAINT `fk_permission_action_id1`
    FOREIGN KEY (`action_id`)
    REFERENCES `bug_tracking`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_resource_id1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `bug_tracking`.`resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bug_tracking`.`role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug_tracking`.`role_permission` ;

CREATE TABLE IF NOT EXISTS `bug_tracking`.`role_permission` (
  `role_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  `valid_from` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valid_to` DATETIME NULL DEFAULT '9999-12-31 23:59:59',
  PRIMARY KEY (`role_id`, `permission_id`),
  INDEX `fk_role_action_role1_idx` (`role_id` ASC),
  INDEX `fk_role_action_permission1_idx` (`permission_id` ASC),
  CONSTRAINT `fk_role_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `bug_tracking`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_permission_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `bug_tracking`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
